### ISSUE TITLE
Target Query mixed up

### ISSUE THREAD

**Issue by Victaphanta** [jnarayan81/parallelLastz#1]
Hi Jitendra.  Thank for making available the script.  I ran it over the last few day, and it seems that the target (--tfile) and query (--qfile) have been mixed up - the results aligned the target to the query.  Is it possible to have a look at your code and see where it has gone wrong - I have not been available to work it out.  Hope you can help.  A

**Comment by Victaphanta** [comment]
I think I worked it out.  Line 132 and 137

$tmp_fh $tfile  should be swapped around

same for 133 and 138

as per manual
"The general format of the LASTZ command line is

    lastz <target> [<query>] [<options>]"

**Comment by jnarayan81** [comment]
Hi,
Thanks for this bug, the files were in fact flipped. 
I push the updates on github. Sync and run ...

**Comment by Victaphanta** [comment]
Thanks Jitendra,

I already modified it myself.  But then I got error regarding multiple sequences for target.  I then split my target into separate files fro each sequence (scaffold).  And I am processing them one at a time.

Is that what I have to do for target files containing multiple sequences – or does you script look after that also?

Adnan

**Comment by jnarayan81** [comment]
Hi,
No, that is not required. You can check the script with testDATA> It works fine with multi-fasta.

Thanks
