### ISSUE TITLE
parallelLastz.pl finds a local lastz binary but exits anyway?

### ISSUE THREAD

**Issue by RussellAndrewEdson** [jnarayan81/parallelLastz#2]
Is line 53 in `parallelLastz.pl` correct?
![Screenshot_2021-06-08 jnarayan81 parallelLastz(1)](https://user-images.githubusercontent.com/8025610/121124138-90b48800-c863-11eb-9f3e-08f5ed66ebd2.png)
That appears to kill the program regardless of whether it finds a local lastz binary. Sure enough, when we ran it locally on our machine it reports that it finds the local lastz binary and then prints that error and kills the process. 

Commenting that entire line out allowed us to run the program properly, so there seems to be an issue with the check.

**Comment by jnarayan81** [comment]
Thank you for informing us; the bug has been resolved. It is now also available through conda at https://anaconda.org/jnarayan81/parallellastz.
